const $=s=>document.querySelector(s),grid=$('#grid'),status=$('#status'),details=$('#details'),player=$('#player'),video=$('#video');let installPrompt,current,hls;
const api=(params)=>fetch('/api/anidash?'+new URLSearchParams(params)).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error||'Could not load');return x});
const titleOf=x=>x.title?.english||x.title?.romaji||x.name||'Untitled';
function card(x){const id=x.id,poster=x.coverImage?.large||x.cover||x.poster||'',title=titleOf(x),meta=x.seasonYear||x.year||x.type||'';return `<button class="card" data-id="${id}" data-title="${encodeURIComponent(title)}" data-poster="${encodeURIComponent(poster)}"><div class="poster"><img src="${poster}" loading="lazy"><span>${meta}</span></div><strong>${title}</strong><small>${x.episodes||x.number||'?'} episodes</small></button>`}
async function home(){status.textContent='Loading…';$('#sectionTitle').textContent='Trending Anime';try{const q=`query{Page(page:1,perPage:25){media(type:ANIME,sort:TRENDING_DESC){id title{english romaji}coverImage{large}seasonYear episodes format}}}`;const r=await fetch('https://graphql.anilist.co',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q})});const x=await r.json();grid.innerHTML=x.data.Page.media.map(card).join('');status.textContent=''}catch{status.textContent='Try again';}}
async function search(){const q=$('#search').value.trim();if(!q)return;status.textContent='Searching…';$('#sectionTitle').textContent='Search Results';try{const x=await api({action:'search',query:q});grid.innerHTML=(x.results||[]).map(card).join('')||'<p>No results found.</p>';status.textContent=''}catch(e){status.textContent=e.message}}
async function openAnime(button){current={id:button.dataset.id,title:decodeURIComponent(button.dataset.title),poster:decodeURIComponent(button.dataset.poster)};details.showModal();$('#detailBody').innerHTML=`<div class="hero" style="background-image:url('${current.poster}')"><h1>${current.title}</h1><p>Loading episodes…</p></div>`;try{let page=1,all=[],x;do{x=await api({action:'episodes',id:current.id,page});all.push(...(x.episodes||[]));page++}while(page<=(x.totalPages||1));$('#detailBody').innerHTML=`<div class="hero" style="background-image:url('${current.poster}')"><h1>${current.title}</h1><p>${all.length} episodes available</p></div><div class="episodes">${all.map(ep=>`<button class="episode" data-episode="${ep.number}"><img src="${ep.image||current.poster}" loading="lazy"><span><strong>E${ep.number} — ${ep.title||'Episode '+ep.number}</strong><small>${ep.filler?'Filler episode':'Tap to watch'}</small></span></button>`).join('')}</div>`}catch(e){$('#detailBody').innerHTML+=`<p>${e.message}</p>`}}
async function play(ep){player.showModal();$('#playerTitle').textContent=`${current.title} · E${ep}`;$('#playerStatus').textContent='Finding video…';if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load();try{const x=await api({action:'source',id:current.id,episode:ep,audio:$('#audio').value});const src=x.sources?.[0]?.url;if(!src)throw Error('No playable source');video.poster=current.poster;if(window.Hls&&Hls.isSupported()){hls=new Hls({maxBufferLength:100,maxMaxBufferLength:120,enableWorker:true});await new Promise((resolve,reject)=>{hls.on(Hls.Events.MANIFEST_PARSED,resolve);hls.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal)reject(Error('Video stream could not be loaded'))});hls.loadSource(src);hls.attachMedia(video)});await video.play()}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=src;await video.play()}else{throw Error('This browser cannot play the video stream')}$('#playerStatus').textContent='';localStorage.setItem('anidash-continue',JSON.stringify({...current,episode:ep}))}catch(e){$('#playerStatus').textContent=e.name==='NotAllowedError'?'Tap play to start the video':e.message}}
grid.addEventListener('click',e=>{const b=e.target.closest('.card');if(b)openAnime(b)});$('#detailBody').addEventListener('click',e=>{const b=e.target.closest('.episode');if(b)play(b.dataset.episode)});$('#searchButton').onclick=search;$('#search').onkeydown=e=>{if(e.key==='Enter')search()};$('.close').onclick=()=>details.close();$('.playerClose').onclick=()=>{video.pause();if(hls){hls.destroy();hls=null}video.removeAttribute('src');video.load();player.close()};$('#audio').onchange=()=>{if(player.open){const ep=$('#playerTitle').textContent.match(/E([\d.]+)$/)?.[1];if(ep)play(ep)}};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.view==='home')home();if(b.dataset.view==='search')$('#search').focus();if(b.dataset.view==='continue'){const x=JSON.parse(localStorage.getItem('anidash-continue')||'null');if(x){grid.innerHTML=card(x);$('#sectionTitle').textContent='Continue Watching'}else{grid.innerHTML='<p>Nothing here yet.</p>'}}});
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true}else alert('In Safari, tap Share, then Add to Home Screen.')};if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');const h=new Date().getHours();$('#greeting').textContent=h<12?'Good morning':h<17?'Good afternoon':'Good evening';home();
